version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: flashscore-matches-db
    restart: always
    environment:
      POSTGRES_DB: matches-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
