version: '3.8'

networks:
  flashscore-network:

services:
  postgres:
    image: postgres:16-alpine
    container_name: flashscore-matches-db
    restart: always
    environment:
      POSTGRES_DB: matches-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - flashscore-network

  flashscore-matches-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flashscore-matches-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DATABASE_URI: jdbc:postgresql://postgres:5432/matches-db
      USER: user
      PASSWORD: password
    depends_on:
      - postgres
    networks:
      - flashscore-network

volumes:
  postgres-data:

